magfest/infrastructure

magfest_state/salt/cloud/files/cloud.maps.d/reggie-prod-bytegen-2019.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-prod-bytegen-2019-profiles.conf
@RobRuana is showing me how to provision new servers with the salt states, so I'm making a PR for a new event called ByteGen, which is approximately 8x better than BitGen.
=> added new bytegen event for testing

magfest_state/salt/cloud/files/cloud.profiles.d/reggie-prod-bytegen-2019-profiles.conf
Fixed a copy/paste issue in my previous commit.
=> fixed typo in bytegen

reggie_config/bytegen/README.md, reggie_config/bytegen/init.yaml
This goes along with our previous config and will add some actual data for https://bytegen.reggie.magfest.org
=> added bytegen as an actual event in the reggie_config

reggie_config/super_2019/init.yaml
=> Add rock_island_dealine: 2018-11-17

reggie_config/super_2019/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-292.
=> Update Dept Head Checklist for Super 2019

reggie_config/super_2019/init.yaml
=> Moves dealer payment deadline to November 4 at 11:59 PM

reggie_config/super_2019_staging/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-328.
=> Add MITS to staging

reggie_config/super_2019/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-322.
=> Add MITS deadlines

reggie_config/super/init.yaml, reggie_config/super_2019/init.yaml
Fixes the volunteer checklist portion of https://jira.magfest.net/browse/MAGDEV-292. ... I think.
=> Update volunteer checklist order and add agreements

reggie_config/super/init.yaml
=> Add missing food step

reggie_config/super_2019/init.yaml
Now people will be able to actually fill out their MPoints!
=> Add 2018 Treasury MPoints Spreadsheet URL

reggie_config/super_2019/init.yaml
=> Extend Supporter deadline to Nov 15th

reggie_config/super/init.yaml
Updated locations an added missing Panels rooms, and few other rooms
=> Fix locations 

reggie_config/super_2019/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-361.
=> Move up shirt deadline

reggie_config/super_2019/init.yaml
Adds the checklist items in parallel to https://github.com/magfest/ubersystem/pull/3373.
=> Add MIVS Checklist items

reggie_config/super/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-359.
=> Update schedule locations for Super 2019, part 2

reggie_config/super/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-371.
=> Add new rooms for Super 2019

reggie_config/super/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-397. Fixes https://jira.magfest.net/browse/MAGDEV-383.
=> Update room locations for Super 2019

reggie_config/super/init.yaml
per shaxberd via Slack in #stops
=> Update Pathfinder rooms

reggie_config/onsite.reggie.magfest.org/init.yaml
I'm gonna merge this in right away since it's just config for a server which hasn't even been provisioned yet.
FWIW, ``onsite.reggie.magfest.org`` is the hostname and minion id of the main server where everything will be running.  I'll be spinning up a second box just to have a second web working running, though realistically we'd almost certainly be fine with only one server.
=> added onsite config

reggie_config/reggie.magfest.org/init.yaml
=> turned on redirect to onsite server

reggie_config/super_2019/init.yaml
So many people registering at 2am on Sunday morning!
=> bumped badge count again!

reggie_config/super_2019/init.yaml
=> bumped badges to number that represents what we actually have

reggie_config/onsite.uber.magfest.org/init.yaml, reggie_config/super_2019_prod/init.yaml
This also turns off maintenance mode for prod.  This is the followup to https://github.com/magfest/infrastructure/pull/63/files
=> this redirects onsite back to reggie instead of the other way around

magfest_state/salt/cloud/files/cloud.maps.d/reggie-west-2019.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-west-2019-profiles.conf, reggie_config/west/init.yaml
These are the config changes which I've already deployed which were used to deploy https://west2019.reggie.magfest.org
=> Magwest 2019

reggie_config/west/init.yaml
I had to add tshirt sizes in order for staffer imports from last year to work properly.  I did this several days ago and neglected to file a PR until now.
=> added west tshirt sizes

magfest_state/salt/cloud/files/cloud.maps.d/reggie-stock-2019.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-stock-2019-profiles.conf, reggie_config/stock/init.yaml, reggie_config/stock_2019/init.yaml
I've added the server https://stock2019.reggie.magfest.org with this PR.
Rob had already created some data files for Stock 2019 as part of his testing of this infrastructure, which is why I'm modifying existing files for Stock 2019 even though this is the first time that server has really existed.
I'm gonna merge this in now since it's already been deployed, and I want to make sure that mcp is able to run off of the master branch.
=> Magstock 2019

reggie_config/west/init.yaml, reggie_config/west_2019/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-431, probably.
=> Add MAGWest 2019 badge prices and donation tiers

reggie_config/stock/init.yaml
=> Turn groups off in the correct plugin

reggie_config/west_2019/init.yaml
I didn't know what to do with the default_price variable; does it need to be set to null to make the table numbers take effect? If not, it should be fine, otherwise, please adjust as necessary.
=> Update vendor table and badge prices

reggie_config/west_2019/init.yaml
I forgot how table prices actually work. Whoops
=> Update table prices to work with cumulative pricing

reggie_config/stock_2019/init.yaml
Attempting to fix a deployment error.
=> Add printed_signs description

reggie_config/west_2019/init.yaml
Implements the config-related changes in https://jira.magfest.net/browse/MAGDEV-486.
=> Update dealer config for West 2019

reggie_config/west/init.yaml, reggie_config/west_2019/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-515.
=> Add config for West 2019 dept head and volunteer checklists

reggie_config/west/init.yaml
Not being able to test config locally makes for fun and exciting adventures!
=> Add missing values for MAGWest dept head checklist

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020-staging.map, magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2020-profiles.conf, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2020-staging-profiles.conf
We're spinning up Super 2020 servers!
=> Add Super 2020 server profiles

reggie_config/super/init.yaml, reggie_config/west/init.yaml
Config for https://github.com/magfest/ubersystem/pull/3470.
=> Add default values for staff_event_shirt for Super and West

reggie_config/west/init.yaml
You actually need to work 8 hours to earn a shirt for MAGWest!
=> Set West hours for shirt to 8

reggie_config/super/init.yaml
Part of https://jira.magfest.net/browse/MAGDEV-522.
=> Add config for Super Panels

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020.map
We don't need 10 whole web servers on the first deploy. I _GUESS_.
=> Only spin up 2 web servers for prod Super

reggie_config/super_2020_staging/init.yaml
I promised Danielle I'd give her the link for marketplace apps ahead of time, so we need to open dealer reg early on staging.
=> Open dealer reg for staging Super 2020

reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-541.
=> Change dealer-related terms to Marketplace

reggie_config/super_2019/init.yaml, reggie_config/super_2020/init.yaml, reggie_config/west_2019/init.yaml
Some panel config options were renamed to be more consistent with other options.
=> Update panel config names

reggie_config/super_2020/init.yaml
=> Unopen prereg for Super 2020

reggie_config/super_2020/init.yaml
Also updating a few prereg-related dates while we remember!
=> Update badge prices for Super 2020

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020-perf.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-perftest-2020-profiles.conf, reggie_config/load/init.yaml, reggie_config/load/loadbalancer.yaml
I did two things in this PR:
1) Added the cloud profile and map files for the load testing stack.
2) Updated the "load" pillar data to match the staging environment.
=> load testing config

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Emergency changes to update merch to be the correct prices and descriptions, since merch appears on staff badge pages.
=> Update merch for Super 2020

reggie_config/super/init.yaml
We have the column still, so we need the definitions for the options.
=> Re-add sweatpants opts

reggie_config/super_2020/init.yaml
=> Move MAGFest 2020 to end on Sunday instead of Monday

reggie_config/init.yaml, reggie_config/labs/init.yaml, reggie_config/stock/init.yaml, reggie_config/super/init.yaml
Goes with https://github.com/magfest/ubersystem/pull/3513.
=> Remove Supporter badge type and add Contractor badge type

reggie_config/super_2020/init.yaml
We told people 3pm, it should be set to 3pm!
=> Open Super 2020 Prereg at 3pm, not noon

reggie_config/init.yaml
This will put this on our prereg page.
=> Add new privacy policy to our config

reggie_config/west_2019/init.yaml
=> Allow badge #7 for Staff

reggie_config/west/init.yaml
Also adds Guest and Rockstar ribbons.
=> Update badge ranges for West 2019

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-597.
=> Update Super 2020 Auction Start to be Sunday

reggie_config/west_2019/init.yaml
I... I think we're probably ready to change modes now!
=> Set West 2019 to post-con mode, turn off emails and SMS

reggie_config/west_2019/init.yaml
=> Unset send_emails to false for West

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-615.
=> Update band checklist deadlines

reggie_config/super_2020/init.yaml
This will actually enable the new checklist step added for https://jira.magfest.net/browse/MAGDEV-288.
=> Add band deadline for rehearsal

reggie_config/super_2020/init.yaml
=> Change dealer_payment_due to 11/01/2019

reggie_config/super_2020/init.yaml
https://jira.magfest.net/browse/MAGDEV-631
=> Remove Panels limit

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-635.
=> Update dept head checklist dates

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-636. Also correct an error in the last PR where I removed the wrong checklist item.
=> Add social media and mediatron checklist items

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-637 -- this updates the "root" text for the different checklist items.
=> Update Super checklist item descriptions

reggie_config/super/init.yaml
Smart quotes break our config deploy.
=> Remove smart-quotes

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-637.
=> Add new dept head checklist form URLs

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-637.
=> Update text for Dept Head Checklist and add checklist item

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-657.
=> Push back dept head checklist dates

reggie_config/init.yaml, reggie_config/stock/init.yaml, reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-671. Also updates the developer email to use the MAGFest-only mailing list.
=> Enable volunteer agreement and offsite staffer perks link for Super

reggie_config/super/init.yaml
We're changing the volunteer perks now!
=> Update number of hours needed to earn a shirt for Super

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml
Also includes some tweaks to wording for other checklist steps. Part of fixing https://jira.magfest.net/browse/MAGDEV-668.
=> Add guidebook schedule step to dept head checklist

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-682.
=> Update MIVS checklist deadlines

reggie_config/super_2020/init.yaml
I misunderstood what was needed -- we don't want to remove these steps, only make them non-completable, which I've done by using a "start" date.
=> Re-add steps to MIVS checklist

reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-663.
=> Add credits name to super volunteer checklist

reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-641.
=> Update "own table" option for guest groups

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-729.
=> Add kick-in stocks for Super 2020

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-629. Also part of fixing https://jira.magfest.net/browse/MAGDEV-628.
Note that we'll have to delete automated email categories and re-generate them, we should make sure doing so works in staging.
=> Make "indie handbook" MIVS checklist step editable

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-749.
=> Update Super printed badge deadline

reggie_config/super/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-751.
=> Update schedule locations for Super 2020

reggie_config/super_2020/init.yaml
See https://github.com/magfest/infrastructure/pull/202 for an explanation.
=> Merge badge range for staff and contractors

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020-onsite-staging.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2020-onsite-staging-profiles.conf, reggie_config/init.yaml, reggie_config/loadbalancer.yaml, reggie_config/onsite-staging-super-2020.reggie.magfest.org/init.yaml
I did two things here:
1) I added an onsite staging server for super 2020.
2) In order to support this, I updated the states to always pull from events with the same event tag.  I'll call out those changes inline.
=> added onsite staging server and added more event_tag support

reggie_config/super_2020/init.yaml
=> Enable MIVS Selling checklist step

reggie_config/super/init.yaml
https://jira.magfest.net/browse/MAGDEV-751.
=> Update schedule items again

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-756.
=> Enable MIVS Handbook checklist step

reggie_config/super_2020/init.yaml
I forgot to update the year of the relevant dates!
=> Enable handbook step in 2019

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-762.
=> Add badge stocks instead of max_badges

reggie_config/super_2020/init.yaml
Reverts magfest/infrastructure#212.
TOO SOON. TOO SOON!!!!
=> Revert "Add badge stocks instead of max_badges"

reggie_config/super_2020/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-782.
=> Add drop_shifts_deadline

reggie_config/super_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-785.
=> Activate MIVS training step

reggie_config/onsite/init.yaml, reggie_config/super_2020_prod/init.yaml
I forgot to check this in last night before going to bed, but this was deployed in the middle of the night last night.
=> moved onsite

reggie_config/stock/init.yaml
This is causing the server to fail to run.
=> Remove contractor_badge from Stock config

reggie_config/staging-west.reggie.magfest.org/init.yaml
We want to see what's on the prereg page to get an idea of what assets are needed for it. I _think_ this will do it.
=> Update West Staging to allow viewing prereg page

reggie_config/stock_2019/init.yaml
Hopefully fixes https://jira.magfest.net/browse/MAGDEV-852.
=> Push Stock2019 back to earlier code

reggie_config/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-870.
=> Re-enable JIRA

reggie_config/west_2020/init.yaml
=> Use master branch for West 2020

reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-901.
=> Update West panels application text

reggie_config/west/init.yaml, reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-877.
=> Initial config update for West 2020

reggie_config/west_2020_staging/init.yaml
=> Add earlier dealer reg start for West Staging

reggie_config/west/init.yaml, reggie_config/west_2020/init.yaml
Updates deadlines and root text for all West department head checklist items
=> Update West Department Head checklist

reggie_config/west_2020/init.yaml
Got new text for the signage step!
=> Update DH checklist text for signage

reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-930.
=> Update West 2020 with new dates

reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-931. Thanks to https://github.com/magfest/ubersystem/pull/3762, these changes will turn off department head checklist items instead of hosing the system.
I also turned off some of the repetitive emails that we've been getting.
=> Update West Dept Head Checklist

reggie_config/west/init.yaml, reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-879.
=> Update West Volunteer Checklist

reggie_config/west_2020/init.yaml
Volunteer_placeholder_deadline is supposed to be a string, not a date. Oops.
=> Fix volunteer_placeholder_deadline

reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-935. Depends on https://github.com/magfest/ubersystem/pull/3769.
=> Turn off volunteer merch-related config items for West

reggie_config/west_2020/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-939.
=> Update West 2020 volunteer checklist deadlines

reggie_config/super_2021/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-954 and https://jira.magfest.net/browse/MAGDEV-953.
=> Update volunteer + dept head checklists

reggie_config/super_2021/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-956.
=> Update volunteer checklist and confirmation page

reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-957.
=> Update Social Media Requests text

reggie_config/super_2021/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-957. Also updates the event dates to the real dates.
=> Add virtual content step to DH checklist

reggie_config/super_2021/init.yaml
Re-enables the dept head checklist, updates the years on all the dates, and removes virtual-event-specific config.
=> Preliminary config updates for Super 2022

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2021.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2021-profiles.conf
Attempting to fix issues with the hostname for Super 2022, e.g., https://github.com/magfest/ubersystem/issues/3785.
=> Update super 2022 salt

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-969. We should change the banner at the top of the page first before merging this.
=> Update MIVS application start and end dates

magfest_state/salt/cloud/files/cloud.maps.d/reggie-west-2021.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-west-2021-profiles.conf
Fixes https://jira.magfest.net/browse/MAGDEV-974.
=> Provision West 2021

reggie_config/west_2021/init.yaml
Adds basic config for virtual West 2021.
=> Add West 2021 config

reggie_config/west_2021/init.yaml
=> Set MAGWest prereg open to not be in the past

reggie_config/super_2022_staging/init.yaml
Reverts magfest/infrastructure#273 now that reg is done reviewing at-con mode.
=> Revert "Set Super staging to at-con mode"

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-978.
=> Update MITS submission deadline

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-980.
=> Change MITS badges per team and contact email

reggie_config/super_2022/init.yaml
Reverts magfest/infrastructure#277
I CAN'T F'ING READ
=> Revert "Update MIVS start/deadline"

reggie_config/super_2022/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-990.
=> Update expected panels response date

reggie_config/super_2022/init.yaml
Fixes part of https://jira.magfest.net/browse/MAGDEV-984.
=> Add config for Super 2022 kickin tiers

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-986.
=> Update dealer config for Super 2022

reggie_config/super_2022/init.yaml
Finishes fixing https://jira.magfest.net/browse/MAGDEV-986, updates attendee badge prices, and updates a couple other important dealer config values.
=> Update table and badge prices

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2021.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2021-profiles.conf
Fixes https://jira.magfest.net/browse/MAGDEV-987 (the rest of the way).
=> Add more web servers for Super 2022

reggie_config/super/init.yaml, reggie_config/super_2019/init.yaml, reggie_config/super_2020/init.yaml
Our shirt sizes for Super keep changing, so it will be easier if we just set them in the event config.
=> Move shirts to be per-event

reggie_config/super/init.yaml, reggie_config/super_2020/init.yaml, reggie_config/super_2022/init.yaml
Part of adding a size option for button-down shirts.
=> Replace sweatpants opts with special merch opts

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-963. Fixes https://jira.magfest.net/browse/MAGDEV-992.
=> Update Volunteer perks link

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2022.map
We've fixed our deploys so now we can actually deploy things properly. Also added more servers for prereg launch.
=> Set up final prereg Super deploy

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-959.
I need some feedback on the shirt deadline before we actually merge this.
=> Update config for Super prereg launch

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1013.
=> Update volunteer checklist deadlines

reggie_config/super_2022/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-996.
=> Add staff shirt sizes

reggie_config/super_2022/init.yaml
We won't merge this until we have the correct form URL, but I wanted to include an update to the name since I named the step the wrong thing initially.
=> Update PPE requests step name and URL

reggie_config/super_2022/init.yaml
Updating config based on https://jira.magfest.net/browse/MAGDEV-1029.
=> Update Super 2022 DH Checklist links

reggie_config/super_2022/init.yaml
=> Fix config errors blocking deploy

reggie_config/super/init.yaml
=> Reorder DH checklist steps

reggie_config/super_2022/init.yaml
=> Update Panels deadline for Super

reggie_config/super_2022/init.yaml
It'd sure be nice if I could test config changes locally.
=> Remove duplicate shirt step from volunteer checklist

reggie_config/super_2022/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1036 and https://jira.magfest.net/browse/MAGDEV-1037.
=> Update config for volunteer and dept checklist emails

reggie_config/super_2022/init.yaml
Also corrects the number of shirts per staffer.
=> Update seller payment deadline for Super

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1040. Also includes some deadline updates that were requested via Slack.
=> Update group discount + deadlines

reggie_config/super_2022/init.yaml
Reverts magfest/infrastructure#333
=> Revert "Update secure document URL"

reggie_config/super_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1048.
=> Add autograph to band checklist

reggie_config/super_2022/init.yaml
Re-enables the training step and adds a new form URL.
=> Update MIVS training step

reggie_config/super_2022/init.yaml
=> Turn on at-con mode for Super 2022

reggie_config/west_2022/init.yaml
This was missing from the base file, whoops.
=> Add description for schedule step

reggie_config/super/init.yaml, reggie_config/west/init.yaml, reggie_config/west_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1091. Fixes https://jira.magfest.net/browse/MAGDEV-1087. Part of fixing https://jira.magfest.net/browse/MAGDEV-1086.
=> Update various West config options

reggie_config/west/init.yaml
Finishes fixing https://jira.magfest.net/browse/MAGDEV-1087.
=> Actually add emergency procedures item

reggie_config/west_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1083. Also disables Tuber as per https://jira.magfest.net/browse/MAGDEV-1090.
=> Update West volunteer checklist dates

reggie_config/west/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1085.
=> Add COVID plugin to magwest deploy

reggie_config/west_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1093.
=> Update single-day badge prices

reggie_config/west/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1092.
=> Add MAGWest TechOps email

reggie_config/west_2022/init.yaml
=> Extend West panels deadline

reggie_config/west/init.yaml
Partly fixes https://jira.magfest.net/browse/MAGDEV-1103. Partly fixes https://jira.magfest.net/browse/MAGDEV-1097.
=> West config updates

reggie_config/west/init.yaml, reggie_config/west_2022/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1104. Partly fixes https://jira.magfest.net/browse/MAGDEV-1103. Partly fixes https://jira.magfest.net/browse/MAGDEV-1097. Fixes https://jira.magfest.net/browse/MAGDEV-1096. Fixes https://jira.magfest.net/browse/MAGDEV-1095.
=> West prereg launch config updates

reggie_config/west/init.yaml
Fixes https://jira.magfest.net/browse/MAGDEV-1110.
=> Update shirt level price

reggie_config/west/init.yaml, reggie_config/west_2022/init.yaml
We also need to fix the CoC URL.
=> Set West prereg to have had already opened

reggie_config/west/init.yaml
A couple of links hadn't been updated and one no longer works.
=> Fix West dept checklist links

reggie_config/west_2022/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1113.
=> Update config for West band checklist

reggie_config/west_2022/init.yaml
This should finish up the config for https://jira.magfest.net/browse/MAGDEV-1113.
=> Update rest of band checklist configs

reggie_config/west_2022/init.yaml
=> Push back volunteer hotel request deadline

reggie_config/west_2022/init.yaml
=> Update West dealer payment due date

reggie_config/west_2022/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1115.
=> Remove extraneous Guest Checklist steps

reggie_config/west_2022/init.yaml
Apparently these deadlines don't work the way I remember them.
=> Re-add shirt deadline

reggie_config/west_2022/init.yaml
Move dealer payment deadline from 7/31 to 8/10 because we're slow :(
=> Postpone dealer payment deadline

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2023.map, magfest_state/salt/cloud/files/cloud.profiles.d/reggie-super-2023-profiles.conf
=> Spin up Super 2023

reggie_config/west_2022_staging/init.yaml
=> Use West's base at_the_con variable for staging

reggie_config/west/init.yaml
=> Make child badges match other badge ranges

reggie_config/super_2023/init.yaml
=> Update Super 2023 dealer prices

reggie_config/super_2023/init.yaml
=> Set the right event dates for Super 2023

reggie_config/super/init.yaml
Part of fixing https://jira.magfest.net/browse/MAGDEV-1117
=> Add config for new panels fields

reggie_config/super/init.yaml, reggie_config/super_2023/init.yaml
Requested via Slack.
I can't see when we said we'd open dealer reg on Monday, so I picked noon.
=> Update panel submission start and deadline

reggie_config/super/init.yaml, reggie_config/super_2023/init.yaml
I knew I'd forgotten something.
=> Add MAGES room and Arena room to panel rooms

reggie_config/super_2023/init.yaml
Turns out noon was not a good guess!
=> Change panels start time

reggie_config/super_2023/init.yaml
Eyyyy let's not open prereg tomorrow k?
=> Push out prereg_open

reggie_config/super_2023/init.yaml
=> Update Super kick-in descriptions

reggie_config/super_2023/init.yaml
Fixes the price bump dates and adds a comment so I stop messing up the price bump dates. Also attempts to clear out dept head and volunteer checklist dates because those are not ready yet.
=> Update even more Super dates

reggie_config/super_2023/init.yaml
=> Fully disable volunteer and dept head checklists

reggie_config/super_2023/init.yaml
=> Turn group badges off

reggie_config/super_2023/init.yaml
=> Shuffle merch stocks around and turn on group badges

reggie_config/web.yaml
=> Please stop running out of DB connections

reggie_config/super_2023/init.yaml
Stop selling shirt sizes that we're now sold out of.
=> Remove sold out shirt sizes

reggie_config/super/init.yaml
Actually I guess I just missed one thing.
=> I missed some things

reggie_config/super_2023/init.yaml
Also fixes the volunteer checklist so that the shifts and placeholder step will actually show up.
=> Update Tech Requirements form

reggie_config/super_2023/init.yaml
Also switches to using the master branch for Super 2023.
=> Add volunteer checklist open date

reggie_config/super_2023/init.yaml
Also adds a step for a to-be-made-soon "Rock Island" checklist type.
=> Update Super 2023 band checklist dates

reggie_config/super_2023/init.yaml
=> Extend MITS submission deadline

reggie_config/super/init.yaml
=> Let "Rock Island" groups actually use Rock Island

docs/index.md
=> Fix the link for Super 2023

reggie_config/super_2023/init.yaml
Also reduces some other badge ranges that are a little crazy
=> Split staff and contractor badges

reggie_config/super_2023/init.yaml
=> Update dealer payment due date

reggie_config/super_2023/init.yaml
The charity auction is NOT held on Thursday.
=> Update charity auction date

reggie_config/super_2023/init.yaml
=> Update schedule with new rooms and name changes

reggie_config/super_2023/init.yaml
Updated the Maryland Tax Info Collection Form for MIVS Indies. 
Dec 11th is hard deadline for our indies to fill in new form URL.
Thanks!
=> update mivs selling url for 2023

reggie_config/super_2023/init.yaml
last two urls for mivs.  sorry these are separate from the selling PR (which we needed in asap).  
we need this deployed prior to sunday dec 11th. 
thank you for merge/deploy!
=> mivs handbook and training urls

reggie_config/super_2023/init.yaml
Also fixes the badge price waived date, which was set for Monday.
=> Update Jam Clinic locations

reggie_config/super_2023/init.yaml
=> Stop auto-waitlisting panels

reggie_config/super_2023/init.yaml
We're close enough to the event that I want to make my life easier by splitting Super off into its own branch for last-minute changes
=> Move Super to event-specific branch

reggie_config/super_2023/init.yaml
=> Add Pathfinder HQ

reggie_config/super_2023/init.yaml
Choo choo it's the registration opening train choo choo
(I am very tired)
=> At-the-con mode time

reggie_config/super_2023/init.yaml
hey look it didn't take me two weeks to remember this time
=> Set post-con mode for Super 2023
