magfest/infrastructure

reggie_config/super_2019/init.yaml

Supermag 2019 registrants must register by 11:59pm monday sept 3 to be eligible to receive hotel booking info.

Update hotel booking information deadline

---

reggie_config/super_2019/init.yaml

Dates are currently placeholder until/unless we get sign off on them. Remember that all dates without specific times are end-of-day.

Add refund_start and refund_cutoff

---

reggie_config/super_2019/init.yaml

I have no idea how I got so confused about this, but I added a Google Docs form URL to the treasury page when it needed to be in the hotel setup page. It's already in the hotel setup page, so we just need to remove the bad treasury link.

Remove erroneous treasury link

---

reggie_config/super/init.yaml

'forge' wasn't quite the right name, since we call it 'the_forge' in the locations enum.

Update the_forge varname so it's in panel_rooms

---

reggie_config/super/init.yaml

This is required for https://github.com/magfest/magprime/pull/267 to work, since we can't add this config via the magprime plugin. Please do not remove this config without also changing the code in our magprime plugin.

Add sweatpants sizes to Super config

---

reggie_config/onsite.reggie.magfest.org/init.yaml

Thus turns off trying to scp backups to the backup server, which is on a Digital Ocean we don't have access to.  We still take backups, but they're not being copied off the server, which we'll want to address in the next few days as we go live.

turned off db backups for onsite server

---

reggie_config/onsite.uber.magfest.org/init.yaml

I renamed the server from onsite.reggie.magfest.org to onsite.uber.magfest.org because the latter is what the techops laptops expect.
I also set at the con mode to False because we don't want to set that until tomorrow at around 4pm.  We'll make another change then.

renamed onsite reggie to onsite uber because of laptop configuration

---

magfest_config/defaults.sls
reggie_config/loadbalancer.yaml

There are two changes here, which I've already tested:
1) We need to NOT set the salt master ip address for the onsite server.  What happens is that the onsite server needs to reach out to mcp.magfest.net instead of using its backnet ip.  So we check whether the environment is "onsite" and then we don't supply the backnet ip in that case.  This is backwards-compatible and also allows our onsite server to work.
2) If the ``reggie:onsite_redirect_host`` pillar entry is set, then HAProxy will now redirect to the configured onsite server.  If not set then HAProxy just works as before.  This is how we'll have the current live site redirect to the onsite server once that's up and running.
I'm going to merge this in right away, since this is what's already running on mcp anyway and I've already …

added onsite redirection

---

reggie_config/onsite.uber.magfest.org/init.yaml
reggie_config/super_2019_prod/init.yaml

As discussed, this throws up the ascii donut art for our prod servers but not the onsite server.

set production to maintenance mode but not for the onsite server

---

magfest_state/salt/cloud/files/cloud.maps.d/reggie-stock-2019-staging.map
magfest_state/salt/cloud/files/cloud.maps.d/reggie-west-2019-staging.map
magfest_state/salt/cloud/files/cloud.profiles.d/reggie-stock-2019-staging-profiles.conf
magfest_state/salt/cloud/files/cloud.profiles.d/reggie-west-2019-staging-profiles.conf

This has already been deployed, so I'm gonna go ahead and just merge this in so that I can switch back to the ``master`` branch on mcp immediately, which I neglected to do last time!
We now have
https://staging-west.reggie.magfest.org
and
https://staging-stock.reggie.magfest.org

Stock west staging

---

reggie_config/stock/init.yaml

We need to not automatically check the waiver checkbox when an attendee is transferring their badge to another attendee. I also added other MAGStock-specific fields to be reset.

Add MAGStock-specific untransferable attributes

---

reggie_config/west_2019/init.yaml

added c.CODE_OF_CONDUCT_URL, c.PREREG_FAQ_URL, and c.CONTACT_URL to be correctly referenced in upcoming launch emails.

Changes to website URLs for reg emails

---

reggie_config/west/init.yaml

This step isn't actually configured and was left in by accident while porting this config from super's yaml

Remove hotel step for MAGWest

---

reggie_config/west_2019/init.yaml

The shirt and printed badge deadlines are already set for August 1st, so we just need to change the Supporter deadline to let people buy kick-ins for a while longer.

Push out Supporter deadline by a month

---

magfest_state/salt/cloud/manager.sls

New deploys are failing because an openssl update broke stuff with Salt (https://github.com/saltstack/salt/issues/49661) -- we're fixing it by updating to the latest version of Salt.

Upgrade Salt on minions to fix openssl error

---

bootstrap-mcp.sh

It's not terribly likely this is being used to deploy new servers, but it's good to update it either way.

Update the other instance of the salt version

---

reggie_config/super/init.yaml

The server can't start if any of these are left blank, so it's silly to do this and hope the correct overrides are in downstream config. Much easier to fix any missing deadlines if the server can start and you can see which one is wrong.

Set default values for Dept Head Checklist deadlines

---

magfest_state/top.sls
reggie_config/web.yaml

The old NGINX method (called `nginx`) was removed, and the formula we used was renamed to just `nginx`, so we have to update our reference to it.

Keep using the new NGINX formula

---

reggie_config/web.yaml

Removing the `ng` means we had to indent one less level, but I didn't realize the blocks had their own indent filters. This should fix it.

Fix manual indents for NGINX config

---

reggie_config/super/init.yaml
reggie_config/west/init.yaml

We're removing the social media fields from our base plugin, as the Panels dept for Super wants the options to be different now. They'll live here instead.

Add social media fields for panelists

---

reggie_config/west_2019/init.yaml

Part of https://jira.magfest.net/browse/MAGDEV-540 -- this updates MAGWest's stock of its kickin levels and their deadlines so we can sell kick-ins until the event.

Presell all kick-in levels until MAGWest 2019

---

reggie_config/west_2019/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-533. Also adds presold one day badges, since we'll need people to select those for their Groupon coupons.

Add Groupon payment method

---

reggie_config/west_2019/init.yaml

We need the printed badge deadline updated to today briefly so we can convert some attendee badges to staff badges. There are some last minute additions (BoD, Employees, etc) that need to be put into the system and given staff badges, but Reggie won't assign additional staff badges after this deadline has passed.

West Printed Badge Deadline Change

---

magfest_state/salt/cloud/files/cloud.maps.d/reggie-super-2020.map

Reverts magfest/infrastructure#114.
We're getting 504 timeouts during the marketplace launch. Needs more servers!

Revert "Only spin up 2 web servers for prod Super"

---

reggie_config/labs/init.yaml
reggie_config/super_2020/init.yaml

Part of fixing https://jira.magfest.net/browse/MAGDEV-544. Also sets the MIVS start date to September 1st for Super 2020, which is MIVS' current launch target.

Update MIVS config variable names

---

reggie_config/super_2020/init.yaml

If MIVS wants to open on 9/1, we actually need to make it open 8/31, because the default open time is 11:59pm.

Account for 11:59pm MIVS start date

---

reggie_config/super_2020/init.yaml

It seems these are breaking deploys. Fun!

Remove smartquotes from Super 2020 Kick-in tiers

---

reggie_config/labs/init.yaml
reggie_config/stock/init.yaml
reggie_config/super/init.yaml

Now that we can import departments and their roles from prior events, having default departments is inconvenient, so we're removing them from our config.

Remove default job locations

---

reggie_config/labs/init.yaml
reggie_config/super/init.yaml

We configure these in the database now, so it should be okay to remove them.

Remove shiftless departments from config

---

reggie_config/west/init.yaml
reggie_config/west_2019/init.yaml

Apparently, you can't override badge ranges in downstream config or you'll get an error like this:
```
sideboard.config.ConfigurationError: configuration validation error(s) (): [(['badge_ranges'], 'staff_badge', VdtValueTooLongError('the value "[\'25\', \'999\', \'7\', \'999\']" is too long.',))]
```
So this removes the 'override' and changes the original instead.

Actually start staff badge range at 7

---

reggie_config/super_2020/init.yaml

This allows us to send guests their checklists even though the new contracts aren't in the system yet.

Temporarily remove contract step for guest groups

---

reggie_config/super_2019/init.yaml

A deploy was run against the old Super instance, causing it to break due to the extreme changes in the code. I've made branches from the latest commits in January for both ubersystem and magprime, and this will pin Super 2019 to those branches so we can get that server back to the proper state.

Pin Super 2019 to appropriate branches

---

reggie_config/super_2020/init.yaml

Finally found what was breaking our deploys -- I had renamed a dept head checklist step in one file but not the other.

Correct name of Treasury step

---

reggie_config/super_2020/init.yaml

We changed the "shifts" step deadline for the Dept Head Checklist, but not the corresponding date that lets us release the volunteer checklist. Now we'll be able to send the email!

Update shifts created to reflect the actual deadline

---

reggie_config/super_2020/init.yaml

YAML files don't use triple-quote strings. Whoops.

Comment yaml file correctly

---

reggie_config/super/init.yaml

We can fulfill existing orders for non-unisex shirts, but we can't continue offering them for preorder. Depends on https://github.com/magfest/ubersystem/pull/3596.

Only presell Unisex shirts for Super

---

reggie_config/super/init.yaml
reggie_config/super_2020/init.yaml

We need to turn this step off for Super 2020 because the new hotel requests system doesn't have a corresponding page. We'll revisit next year.

Turn off hotel eligible step in dept head checklist

---

reggie_config/init.yaml
reggie_config/super_2020/init.yaml

We want contractor badges to be preprinted, but with a range right after staff badges to easily separate them.

Add contractor badge as preassigned badge type

---

reggie_config/super_2020/init.yaml

This was a temporary measure to lock down the schedule until we had a chance to make the code not show our schedule while it was still in progress. Part of fixing https://jira.magfest.net/browse/MAGDEV-733.

Turn off nginx schedule hiding

---

reggie_config/super_2020/init.yaml

These deadlines passed but they need to still be enabled. We don't have a solid deadline for printed badges yet, so I pushed it out to this weekend to give us a few days of breathing room.

Update supporter and printed badge deadlines

---

reggie_config/stock_2019/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-744. West is already in post-con mode so we just need to change Stock.

Put Stock 2019 in post-con mode

---

reggie_config/stock_2019/init.yaml

We made breaking changes for Super, so we can't deploy to older instances. We'll get around this by pinning Stock to West's branch, which should be compatible.

Pin Stock to West's code

---

reggie_config/stock_2019/init.yaml

This will hopefully fix deploys to Stock 2019.

Remove Contractor badge from preassigned badge types

---

reggie_config/super_2020/init.yaml

We want contractor badges to be a separate range from staff badges _for our badge export_ so that we can easily put "Contractor" stickers on those badges. HOWEVER, when it comes to assigning blank badges, we want to use one range of blank badges for both Staff and Contractors.
Our plan was to use separate ranges for the export and then merge them afterwards. The catch here is that the system doesn't support two sets of ranges for one badge type -- because the guest badge range was splitting staff and contractor ranges, we wouldn't have been able to merge the badge types' ranges properly. So to fix that we're rejiggering the ranges before the export. After the export, both staff and contractor badges will use the range 25, 2999.

Make staff and contractor badge ranges mergeable

---

reggie_config/super_2020/init.yaml

Reverts magfest/infrastructure#213
We *should* be ready for this now that the code changes are live.

Revert "Revert "Add badge stocks instead of max_badges""

---

reggie_config/super/init.yaml

The default of 500 is too low and our Marketplace head can't see all dealer groups, so we're increasing it for now.

Increase row load limit for groups page

---

reggie_config/onsite.uber.magfest.org/init.yaml

This is a tweak to the onsite server settings, to get https://onsite.reggie.magfest.org/ working (it's still in test mode).

tweaked onsite settings

---

magfest_state/docker_magbot/init.sls
magfest_state/top.sls
magfest_state/zabbix/init.sls
magfest_state/zabbix/zabbix_agentd.conf
reggie_config/onsite/db.yaml
reggie_config/onsite/init.yaml
reggie_config/onsite/loadbalancer.yaml
reggie_config/onsite/scheduler.yaml
reggie_config/onsite/web.yaml
reggie_config/onsite/worker.yaml

Three changes here:
1) Checking in a docker_magbot change which has been hanging around uncommitted for awhile.
2) Adding pillar files for the ``onsite`` env.  These are mostly just copies of the ``prod`` env files, with a few tweaks (e.g. the onsite server is currently set to ``dev_box: true``).
3) Checking in the ``zabbix`` states that the techops folks asked us to add.  These are mostly taken from https://github.com/magfest/salt-rules/blob/master/zabbix/init.sls

added files for onsite

---

reggie_config/super_2020/init.yaml

We accidentally set groups to go offline tonight instead of last night, which is why it was saying the price would go up rather than that group preregistration would go away at midnight last night.
This also stopped some emails from going out until tomorrow.  I've already deployed this fix the the onsite tasks server which handles the emails (which is the only place it really matters at the moment).

fixed group_prereg_takedown

---

reggie_config/super_2020_staging/init.yaml

The staging server should be post-con so we can properly test post-con emails.

Make staging server post-con

---

reggie_config/stock/init.yaml

Somehow this config option got unset, causing the server to still crash.

Fix Stock preassigned badge types. Again.

---

reggie_config/stock/init.yaml

We only offer up to 4XL shirts for MAGStock.

Remove 5XL shirt from MAGStock kick-in options

---

reggie_state/reggie_deploy/db.sls

Ok, so I eventually figured out the issue.
Apparently the ``expr`` utility returns a non-zero exit code if the result of the math it's doing is ``0``.  So saying
```bash
FOO=$(expr 7- 6)
```
returns a 0 exit code, but saying
```bash
FOO=$(expr 7 - 7)
```
returns a 1 exit code, which is why our script was failing.
There's not a command line option we can use to tell ``expr`` to not do this, but an easy workaround is to just add a ``|| true`` to the end of the line, which is a common way to tell bash to ignore a nonzero exit code.

fix stock prod deploy

---

reggie_config/west_2020/init.yaml

(Hopefully) fixes the 500 error when trying to access West's volunteer checklist.

Use correct URLs for volunteer checklist

---

reggie_config/west_2020/init.yaml

I'm pretty sure we're not going to physically print any badges prior to the event, so the deadline for printed badges can be the same as the eschaton.

Extend deadline for Staff badges

---

reggie_config/super_2021/init.yaml

The "hotel eligible" checklist step is actually commented out from Super 2020 because we used Tuber for hotel rooms, so we still don't want it.

Re-remove hotel eligible checklist step

---

reggie_config/init.yaml

We have no immediate plans to use attendee accounts, so we're turning them off for now.

Turn off Attendee Accounts

---

reggie_config/super_2022/init.yaml

Attendees under 12 can't register, so we need to make a new age group for them and adjust the under_13 age group.

Separate 12 year olds from other ages

---

reggie_config/super_2022/init.yaml

A lot of these are just guesses based on what I know is happening, but we need to update at least some of them before sending emails out to volunteers.

Update prereg-relevant dates

---

reggie_config/super/init.yaml
reggie_config/super_2020/init.yaml

Moves the "staff event shirt" config from the default Super file to the Super 2020 file.

Remove "staff event shirt" config from Super 2022

---

reggie_config/super_2022/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-1032. The age groups are a little strange-looking here because it's best not to touch existing age groups.

Allow 5-11 year olds to register

---

reggie_config/super_2022/init.yaml

We need more blank staff badges than the default, and I don't feel like futzing around with the export mode.

Increase number of blank staff badges

---

magfest_state/salt/cloud/files/cloud.profiles.d/reggie-west-staging-profiles.conf

Something is going weird with deploying to staging, so we're going to see if it works when you do not reconfigure the staging server's event year dynamically.

Update West staging event year

---

reggie_config/west/init.yaml

GitHub repos now use the 'main' branch as the default branch, so we need to tell Salt that's the right branch to use.

Use 'main' branch for covid plugin

---

reggie_config/west_2022/init.yaml

Fixes https://jira.magfest.net/browse/MAGDEV-1096. It looked very silly having an unordered list be center-aligned.

Make Room Signage description left-aligned

---

reggie_config/west/init.yaml

Part of fixing https://jira.magfest.net/browse/MAGDEV-1103. We need to rename the super supporter in donation_tier to give it the correct amount.

Make Jet Tier season-level

---

reggie_config/west/init.yaml

We aren't doing them this year! Staffers will still get an event shirt after working hours_for_shirt, this just removes the 'wear on-shift' staff shirt.

Remove staff shirts from west

---

reggie_config/west_2022/init.yaml

Reflects similar changes made for Super. Attendees under 5 still can't register. :( Part of fixing https://jira.magfest.net/browse/MAGDEV-1105.

Override age groups to reflect COVID policies

---

reggie_config/west_2022/init.yaml

Part of fixing https://jira.magfest.net/browse/MAGDEV-1100.

Standardize kick-in icon names

---

reggie_config/super_2023/init.yaml

Missed this when setting up 2023's config.

Set post-con to false for Super 2023

---

reggie_config/init.yaml

We always want to print extra staff badges out and I keep forgetting how this works. Now we automatically get at least 50.

Add extra staff badges for all events

---

reggie_config/super_2023/init.yaml

We need to run Super 2023 with some major changes that we don't want in MAGWest, so we're going to run it off a feature branch until West is over.

Use temporary feature branch for Super 2023

---

reggie_config/super/init.yaml

Right now the system is only showing us 750 dealers, but we need it to show us a bit more than that.

Increase dealer application limit

---

reggie_config/super_2023/init.yaml

We don't need to collect a size for the ULTIMATE tier that I know of, so we need to turn off this field.

Remove special merch opts

---

reggie_config/super_2023/init.yaml

Volunteers for Super no longer have a shirt in their perks, so we should set hours_for_shirt to none

Remove event shirts for volunteers

---

reggie_config/super_2023/init.yaml

We were still using Super 2021's age group policy, which was slightly different from 2020's because kids under 5 couldn't attend. Our FAQs state that kids under six get a discount, so we need to fix this.

Fix age ranges for discount policy

---

reggie_config/super_2023/init.yaml

We don't really use this step anymore, but it doesn't show up unless you set a group as having payment owed so it's safe to set a deadline for this step.

Add W9 deadline to checklists

---

reggie_config/super_2023/init.yaml

This will allow us to actually assign blank staff badges as Staff badges.

Merge Staff and Contractor badge ranges
